array
TRACE START [%d-%d-%d %d:%d:%d]
%w%f %w%d     -> array_map('strlen', array (0 => 'a', 1 => 'bb', 2 => 'ccc')) /%s/array_map.php:5
%w%f %w%d       -> strlen('a') /%s/array_map.php:0
%w%f %w%d       -> strlen('bb') /%s/array_map.php:0
%w%f %w%d       -> strlen('ccc') /%s/array_map.php:0
%w%f %w%d     -> gettype(array (0 => 1, 1 => 2, 2 => 3)) /%s/array_map.php:7
%w%f %w%d     -> file_get_contents('/tmp/%s') /%s/array_map.php:9